apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-confs
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
    
    }
    output {
        elasticsearch {
            hosts => [ "elasticsearch:9200" ]
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.5.4
        ports:
        - containerPort: 5044
        volumeMounts:
          - name: conf-volume
            mountPath: /usr/share/logstash/config
          - name: data-volume
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: conf-volume
        configMap:
          name: logstash-confs
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: data-volume
        configMap:
          name: logstash-confs
          items:
            - key: logstash.conf
              path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-svc
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: LoadBalancer

